update README.md add import
marmelab/ra-auth-acl pull request #5
Opened 2019-09-14 07:34 UTC by Julian-B90

Add `import { ResourceWithPermissions } from 'ra-auth-acl';` to first example.

2019-09-14 13:11 UTC, djhi requested changes

2019-09-14 13:11 UTC, djhi commented on README.md
> +-   **enabled**: Display the resource or not.
Why the two spaces?

2019-09-15 12:56 UTC, Kmaschta commented on README.md
> +-   **enabled**: Display the resource or not.
It must be a linter, I guess

2019-09-15 12:56 UTC, Kmaschta commented
Thanks!

2019-09-15 12:56 UTC, merged